version: "2"
services:
  nginx:
    image: justincarmony/nginx-hello-world
    expose:
      - 8080

  app1:
    image: justincarmony/node-redis-hello-world
    expose:
      - 8888

  app2:
    image: justincarmony/node-redis-hello-world
    expose:
      - 8888

  redis:
    image: redis
    expose:
      - 6379
